groups:
  - name: alert_rules

    rules:

      - alert: InstanceDown
        expr: up == 0
        for: 1m

        labels:
          severity: critical

        annotations:
          summary: "Instance Down"
          description: "{{ $labels.instance }} has been down for more than 1 minute."

      - alert: PrometheusDown
        expr: up{job="prometheus"} == 0
        for: 1m

        labels:
          severity: critical

        annotations:
          summary: "Prometheus Down"
          description: "Prometheus server is not reachable."

      - alert: HighCPUUsage
        expr: process_cpu_seconds_total > 1
        for: 2m

        labels:
          severity: warning

        annotations:
          summary: "High CPU Usage"
          description: "CPU usage is above the threshold."
